

export const Car = [
    {
      img: '/car1.png',
      price: '20000',
      kilometre: '5000',
      type: 'SUV',
      name: 'Toyota Rav4',
      year: '2022',
      fuelType: 'Petrol',
      color: 'Red',
      transmission: 'Automatic',
      engineSize: '2.5L',
      horsepower: 203,
      doors: 5,
      seatingCapacity: 5,
      description: 'A reliable SUV with modern features and low mileage.',
      features: ['GPS', 'Air Conditioning', 'Leather Seats', 'Bluetooth', 'Backup Camera'],
      condition: 'New',
      location: 'Paris, France',
      sellerContact: 'contact@toyota-dealer.com',
    },
    {
      img: '/car2.png',
      price: '15000',
      kilometre: '15000',
      type: 'Sedan',
      name: 'Honda Civic',
      year: '2020',
      fuelType: 'Diesel',
      color: 'Blue',
      transmission: 'Manual',
      engineSize: '1.6L',
      horsepower: 120,
      doors: 4,
      seatingCapacity: 5,
      description: 'A compact sedan with excellent fuel efficiency.',
      features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
      condition: 'Used',
      location: 'Lyon, France',
      sellerContact: 'contact@honda-lyon.com',
    },
    {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      {
        img: '/car2.png',
        price: '15000',
        kilometre: '15000',
        type: 'Sedan',
        name: 'Honda Civic',
        year: '2020',
        fuelType: 'Diesel',
        color: 'Blue',
        transmission: 'Manual',
        engineSize: '1.6L',
        horsepower: 120,
        doors: 4,
        seatingCapacity: 5,
        description: 'A compact sedan with excellent fuel efficiency.',
        features: ['Bluetooth', 'Cruise Control', 'Heated Seats', 'Parking Sensors'],
        condition: 'Used',
        location: 'Lyon, France',
        sellerContact: 'contact@honda-lyon.com',
      },
      
  ];

  export const PresentationImage: string[] =[
      '/hero.png',
      '/p2.png',
      '/p3.png',
      
  ]